a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("ADDITION =", a + b)
print("SUBTRACTION =", a - b)
print("MULTIPLICATION =", a * b)
print("DIVISION =", a / b)